/* Datos de demostración: se cargan únicamente en la base IndexedDB separada. */
const DEMO_COUNTRIES = `Afganistán|Albania|Alemania|Andorra|Angola|Antigua y Barbuda|Arabia Saudí|Argelia|Argentina|Armenia|Australia|Austria|Azerbaiyán|Bahamas|Bangladés|Barbados|Baréin|Bélgica|Belice|Benín|Bielorrusia|Birmania|Bolivia|Bosnia y Herzegovina|Botsuana|Brasil|Brunéi|Bulgaria|Burkina Faso|Burundi|Bután|Cabo Verde|Camboya|Camerún|Canadá|Catar|Chad|Chile|China|Chipre|Colombia|Comoras|Corea del Norte|Corea del Sur|Costa de Marfil|Costa Rica|Croacia|Cuba|Dinamarca|Dominica|Ecuador|Egipto|El Salvador|Emiratos Árabes Unidos|Eritrea|Eslovaquia|Eslovenia|España|Estados Unidos|Estonia|Esuatini|Etiopía|Filipinas|Finlandia|Fiyi|Francia|Gabón|Gambia|Georgia|Ghana|Granada|Grecia|Guatemala|Guinea|Guinea-Bisáu|Guinea Ecuatorial|Guyana|Haití|Honduras|Hungría|India|Indonesia|Irak|Irán|Irlanda|Islandia|Islas Marshall|Islas Salomón|Israel|Italia|Jamaica|Japón|Jordania|Kazajistán|Kenia|Kirguistán|Kiribati|Kuwait|Laos|Lesoto|Letonia|Líbano|Liberia|Libia|Liechtenstein|Lituania|Luxemburgo|Macedonia del Norte|Madagascar|Malasia|Malaui|Maldivas|Malí|Malta|Marruecos|Mauricio|Mauritania|México|Micronesia|Moldavia|Mónaco|Mongolia|Montenegro|Mozambique|Namibia|Nauru|Nepal|Nicaragua|Níger|Nigeria|Noruega|Nueva Zelanda|Omán|Países Bajos|Pakistán|Palaos|Palestina|Panamá|Papúa Nueva Guinea|Paraguay|Perú|Polonia|Portugal|Reino Unido|República Centroafricana|República Checa|República del Congo|República Democrática del Congo|República Dominicana|Ruanda|Rumanía|Rusia|Samoa|San Cristóbal y Nieves|San Marino|San Vicente y las Granadinas|Santa Lucía|Santo Tomé y Príncipe|Senegal|Serbia|Seychelles|Sierra Leona|Singapur|Siria|Somalia|Sri Lanka|Sudáfrica|Sudán|Sudán del Sur|Suecia|Suiza|Surinam|Tailandia|Tanzania|Tayikistán|Timor Oriental|Togo|Tonga|Trinidad y Tobago|Túnez|Turkmenistán|Turquía|Tuvalu|Ucrania|Uganda|Uruguay|Uzbekistán|Vanuatu|Ciudad del Vaticano|Venezuela|Vietnam|Yemen|Yibuti|Zambia|Zimbabue`.split('|');

const DEMO_CATEGORIES = [
  ['Filosofía','Define el concepto y sitúalo en su tradición o autor principal.',`acto y potencia|aporía|ataraxia|categorías aristotélicas|cogito cartesiano|contrato social|dialéctica hegeliana|epojé fenomenológica|eterno retorno|imperativo categórico|intencionalidad|materialismo histórico|monadología|noúmeno|principio de razón suficiente|problema de los universales|teodicea|trascendental|velo de la ignorancia|voluntad de poder`],
  ['Matemáticas','Formula la definición y señala una propiedad o aplicación característica.',`álgebra de Boole|anillo conmutativo|cardinalidad|convergencia uniforme|curvatura gaussiana|determinante jacobiano|distribución normal|espacio de Banach|espacio de Hilbert|grupo abeliano|homeomorfismo|integral de Lebesgue|lema de Zorn|matriz hermítica|método de Montecarlo|número trascendente|serie de Fourier|teorema espectral|topología cociente|variedad diferenciable`],
  ['Física','Explica el principio físico, sus magnitudes relevantes y el régimen donde se aplica.',`acción de Hamilton|bosón de Higgs|campo electromagnético|constante de Planck|decoherencia cuántica|ecuación de Schrödinger|efecto Casimir|efecto Doppler|entropía termodinámica|espacio-tiempo de Minkowski|fermión|invariancia gauge|ley de Gauss|momento angular|principio de equivalencia|principio de incertidumbre|radiación de cuerpo negro|segunda ley de la termodinámica|simetría CPT|tensor energía-momento`],
  ['Biología','Define el proceso o estructura e indica su función biológica principal.',`alosterismo|apoptosis|ARN interferente|bomba sodio-potasio|ciclo de Krebs|deriva genética|epigenética|especiación alopátrica|fosforilación oxidativa|homeobox|impronta genómica|membrana plasmática|operón lac|pleiotropía|recombinación homóloga|selección estabilizadora|simbiosis endosimbiótica|transcripción genética|ubiquitinación|vía de señalización`],
  ['Química','Describe la estructura, el mecanismo o la ley y aporta un ejemplo representativo.',`ácido de Lewis|afinidad electrónica|catálisis heterogénea|cinética de Michaelis-Menten|complejo de coordinación|equilibrio químico|estereoquímica|hibridación orbital|ley de Hess|mecanismo SN2|nucleófilo|orbital molecular|potencial redox|principio de Le Châtelier|reacción de Diels-Alder|regla de Hückel|solvatación|tampón químico|teoría VSEPR|titulación ácido-base`],
  ['Astronomía','Identifica el fenómeno u objeto y explica qué información aporta a la astronomía.',`agujero negro de Kerr|barión acústico|brazo espiral|candela estándar|corrimiento al rojo|diagrama de Hertzsprung-Russell|disco de acreción|enana blanca|estrella de neutrones|fondo cósmico de microondas|límite de Chandrasekhar|materia oscura|método del tránsito|nucleosíntesis estelar|paralaje estelar|púlsar|secuencia principal|supernova de tipo Ia|unidad astronómica|variable cefeida`],
  ['Informática','Define la idea y señala el problema computacional que resuelve o modeliza.',`árbol B|autómata finito|complejidad NP|condición de carrera|consistencia eventual|contenedor de software|criptografía asimétrica|estructura heap|función hash|grafo acíclico dirigido|inmutabilidad|máquina de Turing|normalización de bases de datos|programación dinámica|recorrido en anchura|recorrido en profundidad|semáforo de concurrencia|sistema distribuido|tabla de símbolos|virtualización`],
  ['Economía','Explica el mecanismo económico y distingue sus variables o supuestos fundamentales.',`asimetría de información|coste de oportunidad|curva de Laffer|curva de Phillips|elasticidad-precio|equilibrio de Nash|externalidad|frontera de posibilidades de producción|índice de Gini|inflación subyacente|mercado de futuros|multiplicador fiscal|paridad del poder adquisitivo|prima de riesgo|productividad marginal|riesgo moral|teoría cuantitativa del dinero|trampa de liquidez|ventaja comparativa|valor presente neto`],
  ['Psicología','Define el fenómeno e indica el paradigma experimental o clínico asociado.',`apego seguro|condicionamiento operante|disonancia cognitiva|efecto de mera exposición|efecto halo|función ejecutiva|habituación|heurística de disponibilidad|indefensión aprendida|memoria de trabajo|metacognición|priming|refuerzo intermitente|sesgo de confirmación|teoría de la mente|transferencia psicoanalítica|validez ecológica|zona de desarrollo próximo|motivación intrínseca|procesamiento dual`],
  ['Lingüística','Define el concepto y señala el nivel lingüístico al que pertenece.',`alófono|anáfora|aspecto gramatical|deixis|diglosia|fonema|gramaticalización|hiperonimia|isoglosa|lexicalización|morfema|pragmática|prosodia|recursividad sintáctica|registro lingüístico|semántica composicional|sociolecto|suplemento predicativo|tema y rema|valencia verbal`],
  ['Literatura','Identifica autoría, época, género y relevancia de la obra.',`La Odisea|Edipo rey|La Eneida|La divina comedia|El Decamerón|Don Quijote de la Mancha|Hamlet|El paraíso perdido|Fausto|Orgullo y prejuicio|Frankenstein|Madame Bovary|Crimen y castigo|Guerra y paz|En busca del tiempo perdido|Ulises|La montaña mágica|Cien años de soledad|Pedro Páramo|La casa de los espíritus`],
  ['Historia','Explica el proceso histórico, su cronología aproximada y sus consecuencias.',`Revolución neolítica|democracia ateniense|guerras púnicas|Pax Romana|crisis del siglo III|querella de las investiduras|revolución comercial medieval|Peste Negra|Reforma protestante|Paz de Westfalia|Revolución Gloriosa|Ilustración|Revolución haitiana|Congreso de Viena|Primavera de los Pueblos|Restauración Meiji|Conferencia de Berlín|Revolución rusa|descolonización|Guerra Fría`],
  ['Derecho y política','Define la institución o principio y explica su función dentro del sistema político-jurídico.',`acción de inconstitucionalidad|bicameralismo|control de constitucionalidad|decreto legislativo|división de poderes|estado de derecho|federalismo fiscal|garantía jurisdiccional|habeas corpus|inmunidad parlamentaria|jurisdicción universal|moción de censura|principio de legalidad|recurso de amparo|reserva de ley|soberanía popular|subsidiariedad|sufragio proporcional|tratado internacional|vacatio legis`],
  ['Geología','Describe el proceso, material o estructura y sitúalo en la dinámica terrestre.',`acuífero confinado|batolito|ciclo de Wilson|cratón|discordancia angular|dorsal oceánica|escala de Mohs|falla transformante|isostasia|karstificación|manto litosférico|metamorfismo regional|ofiolita|orogenia|pluma mantélica|subducción|terraza fluvial|till glaciar|vulcanismo intraplaca|zona de Benioff`]
];

window.REPASOS_DEMO_CATALOG = [
  ...DEMO_COUNTRIES.map(text=>({text,hint:''})),
  ...DEMO_CATEGORIES.flatMap(([category,hint,raw])=>raw.split('|').map(text=>({text,hint:`${category}: ${hint}`})))
];
